// Generated by CIRCT firtool-1.37.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Alu(	// <stdin>:3:10
  input  [3:0]  io_opcode,	// src/main/scala/alu.scala:38:16
  input  [63:0] io_ua,	// src/main/scala/alu.scala:38:16
                io_ub,	// src/main/scala/alu.scala:38:16
  output [63:0] io_out,	// src/main/scala/alu.scala:38:16
  output [4:0]  io_cmp	// src/main/scala/alu.scala:38:16
);

  wire         lt = io_ua < io_ub;	// src/main/scala/alu.scala:47:22
  wire         ltu = $signed(io_ua) < $signed(io_ub);	// src/main/scala/alu.scala:48:22
  wire         eq = io_ua == io_ub;	// src/main/scala/alu.scala:49:22
  wire [126:0] _io_out_T_4 = {63'h0, io_ua} << io_ub[5:0];	// src/main/scala/alu.scala:46:21, :66:26
  assign io_out =
    io_opcode == 4'h0 ? io_ua + io_ub : io_opcode == 4'h1 ? _io_out_T_4[63:0] : 64'h0;	// <stdin>:3:10, src/main/scala/alu.scala:53:12, :55:23, :57:{20,26}, :66:{20,26}
  assign io_cmp = {lt, ltu, eq, ~eq & ~lt, ~eq & ~ltu};	// <stdin>:3:10, src/main/scala/alu.scala:47:22, :48:22, :49:22, :51:{18,33,38,42,54,58}
endmodule

module Decode(	// <stdin>:49:10
  input  [31:0] io_inst,	// src/main/scala/decode.scala:101:16
  output [63:0] io_imm,	// src/main/scala/decode.scala:101:16
  output        io_sig_asel,	// src/main/scala/decode.scala:101:16
                io_sig_bsel,	// src/main/scala/decode.scala:101:16
  output [1:0]  io_sig_osel,	// src/main/scala/decode.scala:101:16
  output        io_sig_memEn,	// src/main/scala/decode.scala:101:16
                io_sig_memWe,	// src/main/scala/decode.scala:101:16
                io_sig_rdWe,	// src/main/scala/decode.scala:101:16
  output [4:0]  io_sig_brCond,	// src/main/scala/decode.scala:101:16
  output [3:0]  io_sig_aluop,	// src/main/scala/decode.scala:101:16
  output        io_sig_isJal,	// src/main/scala/decode.scala:101:16
                io_sig_cut32,	// src/main/scala/decode.scala:101:16
                io_sig_err	// src/main/scala/decode.scala:101:16
);

  wire             _signals_T_1 = io_inst[6:0] == 7'h37;	// src/main/scala/decode.scala:117:19
  wire             _signals_T_3 = io_inst[6:0] == 7'h17;	// src/main/scala/decode.scala:117:19, :118:19
  wire             _signals_T_144_isJal = io_inst[6:0] == 7'h6F;	// src/main/scala/decode.scala:117:19, :120:19
  wire [9:0]       _GEN = {io_inst[14:12], io_inst[6:0]};	// src/main/scala/decode.scala:117:19, :123:19
  wire             _signals_T_143_asel = _GEN == 10'h67;	// src/main/scala/decode.scala:123:19
  wire             _signals_T_9 = _GEN == 10'h63;	// src/main/scala/decode.scala:123:19, :127:19
  wire             _signals_T_11 = _GEN == 10'hE3;	// src/main/scala/decode.scala:123:19, :128:19
  wire             _signals_T_13 = _GEN == 10'h263;	// src/main/scala/decode.scala:123:19, :129:19
  wire             _signals_T_15 = _GEN == 10'h2E3;	// src/main/scala/decode.scala:123:19, :130:19
  wire             _signals_T_17 = _GEN == 10'h363;	// src/main/scala/decode.scala:123:19, :131:19
  wire             _signals_T_19 = _GEN == 10'h3E3;	// src/main/scala/decode.scala:123:19, :134:19
  wire             _signals_T_21 = _GEN == 10'h3;	// src/main/scala/decode.scala:123:19, :138:19
  wire             _signals_T_23 = _GEN == 10'h203;	// src/main/scala/decode.scala:123:19, :139:19
  wire             _signals_T_25 = _GEN == 10'h83;	// src/main/scala/decode.scala:123:19, :140:19
  wire             _signals_T_27 = _GEN == 10'h283;	// src/main/scala/decode.scala:123:19, :141:19
  wire             _signals_T_29 = _GEN == 10'h103;	// src/main/scala/decode.scala:123:19, :142:19
  wire             _signals_T_31 = _GEN == 10'h303;	// src/main/scala/decode.scala:123:19, :145:19
  wire             _signals_T_33 = _GEN == 10'h183;	// src/main/scala/decode.scala:123:19, :146:19
  wire             _signals_T_35 = _GEN == 10'h23;	// src/main/scala/decode.scala:123:19, :148:19
  wire             _signals_T_37 = _GEN == 10'hA3;	// src/main/scala/decode.scala:123:19, :149:19
  wire             _signals_T_39 = _GEN == 10'h123;	// src/main/scala/decode.scala:123:19, :150:19
  wire             _signals_T_126_memWe = _GEN == 10'h1A3;	// src/main/scala/decode.scala:123:19, :151:19
  wire             _signals_T_43 = _GEN == 10'h13;	// src/main/scala/decode.scala:123:19, :153:19
  wire             _signals_T_45 = _GEN == 10'h113;	// src/main/scala/decode.scala:123:19, :154:19
  wire             _signals_T_47 = _GEN == 10'h193;	// src/main/scala/decode.scala:123:19, :155:19
  wire             _signals_T_49 = _GEN == 10'h213;	// src/main/scala/decode.scala:123:19, :156:19
  wire             _signals_T_51 = _GEN == 10'h313;	// src/main/scala/decode.scala:123:19, :157:19
  wire             _signals_T_53 = _GEN == 10'h393;	// src/main/scala/decode.scala:123:19, :158:19
  wire [15:0]      _GEN_0 = {io_inst[31:26], io_inst[14:12], io_inst[6:0]};	// src/main/scala/decode.scala:117:19, :123:19, :159:19
  wire             _signals_T_55 = _GEN_0 == 16'h93;	// src/main/scala/decode.scala:159:19
  wire             _signals_T_57 = _GEN_0 == 16'h293;	// src/main/scala/decode.scala:159:19, :160:19
  wire             _signals_T_59 = _GEN_0 == 16'h4293;	// src/main/scala/decode.scala:159:19, :161:19
  wire [16:0]      _GEN_1 = {io_inst[31:25], io_inst[14:12], io_inst[6:0]};	// src/main/scala/decode.scala:117:19, :123:19, :163:19
  wire             _signals_T_61 = _GEN_1 == 17'h33;	// src/main/scala/decode.scala:163:19
  wire             _signals_T_63 = _GEN_1 == 17'h8033;	// src/main/scala/decode.scala:163:19, :164:19
  wire             _signals_T_65 = _GEN_1 == 17'h133;	// src/main/scala/decode.scala:163:19, :165:19
  wire             _signals_T_67 = _GEN_1 == 17'h1B3;	// src/main/scala/decode.scala:163:19, :166:19
  wire             _signals_T_69 = _GEN_1 == 17'h233;	// src/main/scala/decode.scala:163:19, :167:19
  wire             _signals_T_71 = _GEN_1 == 17'h333;	// src/main/scala/decode.scala:163:19, :168:19
  wire             _signals_T_73 = _GEN_1 == 17'h3B3;	// src/main/scala/decode.scala:163:19, :169:19
  wire             _signals_T_75 = _GEN_0 == 16'hB3;	// src/main/scala/decode.scala:159:19, :170:19
  wire             _signals_T_77 = _GEN_0 == 16'h2B3;	// src/main/scala/decode.scala:159:19, :171:19
  wire             _signals_T_79 = _GEN_0 == 16'h42B3;	// src/main/scala/decode.scala:159:19, :172:19
  wire             _signals_T_81 = _GEN == 10'h1B;	// src/main/scala/decode.scala:123:19, :174:19
  wire             _signals_T_83 = _GEN_1 == 17'h9B;	// src/main/scala/decode.scala:163:19, :177:19
  wire             _signals_T_85 = _GEN_1 == 17'h29B;	// src/main/scala/decode.scala:163:19, :180:19
  wire             _signals_T_103_bsel = _GEN_1 == 17'h829B;	// src/main/scala/decode.scala:163:19, :183:19
  wire             _signals_T_89 = _GEN_1 == 17'h3B;	// src/main/scala/decode.scala:163:19, :187:19
  wire             _signals_T_91 = _GEN_1 == 17'h803B;	// src/main/scala/decode.scala:163:19, :190:19
  wire             _signals_T_93 = _GEN_0 == 16'hBB;	// src/main/scala/decode.scala:159:19, :193:19
  wire             _signals_T_95 = _GEN_0 == 16'h2BB;	// src/main/scala/decode.scala:159:19, :196:19
  wire             _signals_T_98_cut32 = _GEN_0 == 16'h42BB;	// src/main/scala/decode.scala:159:19, :199:19
  wire             _GEN_2 =
    _signals_T_81 | _signals_T_83 | _signals_T_85 | _signals_T_103_bsel | _signals_T_89
    | _signals_T_91 | _signals_T_93 | _signals_T_95;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:174:19, :177:19, :180:19, :183:19, :187:19, :190:19, :193:19, :196:19
  wire             _GEN_3 =
    _signals_T_61 | _signals_T_63 | _signals_T_65 | _signals_T_67 | _signals_T_69
    | _signals_T_71 | _signals_T_73 | _signals_T_75 | _signals_T_77 | _signals_T_79;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:163:19, :164:19, :165:19, :166:19, :167:19, :168:19, :169:19, :170:19, :171:19, :172:19
  wire             _GEN_4 =
    _signals_T_43 | _signals_T_45 | _signals_T_47 | _signals_T_49 | _signals_T_51
    | _signals_T_53 | _signals_T_55 | _signals_T_57 | _signals_T_59;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:153:19, :154:19, :155:19, :156:19, :157:19, :158:19, :159:19, :160:19, :161:19
  wire             _GEN_5 =
    _signals_T_43 | _signals_T_45 | _signals_T_47 | _signals_T_49 | _signals_T_51
    | _signals_T_53 | _signals_T_55 | _signals_T_57 | _signals_T_59 | _signals_T_61
    | _signals_T_63 | _signals_T_65 | _signals_T_67 | _signals_T_69 | _signals_T_71
    | _signals_T_73 | _signals_T_75 | _signals_T_77 | _signals_T_79 | _GEN_2;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:153:19, :154:19, :155:19, :156:19, :157:19, :158:19, :159:19, :160:19, :161:19, :163:19, :164:19, :165:19, :166:19, :167:19, :168:19, :169:19, :170:19, :171:19, :172:19
  wire             _GEN_6 = _signals_T_35 | _signals_T_37 | _signals_T_39;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:148:19, :149:19, :150:19
  wire             _GEN_7 =
    _signals_T_21 | _signals_T_23 | _signals_T_25 | _signals_T_27 | _signals_T_29
    | _signals_T_31 | _signals_T_33 | _GEN_6;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:138:19, :139:19, :140:19, :141:19, :142:19, :145:19, :146:19
  wire             _GEN_8 = _signals_T_21 | _signals_T_23 | _signals_T_25 | _signals_T_27;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:138:19, :139:19, :140:19, :141:19
  wire             _GEN_9 =
    _signals_T_9 | _signals_T_11 | _signals_T_13 | _signals_T_15 | _signals_T_17
    | _signals_T_19;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:127:19, :128:19, :129:19, :130:19, :131:19, :134:19
  wire             _GEN_10 =
    _signals_T_9 | _signals_T_11 | _signals_T_13 | _signals_T_15 | _signals_T_17
    | _signals_T_19 | _GEN_8;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:127:19, :128:19, :129:19, :130:19, :131:19, :134:19
  wire             _GEN_11 = _signals_T_144_isJal | _signals_T_143_asel;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:120:19, :123:19
  wire             _GEN_12 = _signals_T_1 | _signals_T_3;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:117:19, :118:19
  wire             _GEN_13 = _signals_T_1 | _signals_T_3 | _GEN_11;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:117:19, :118:19
  wire             _GEN_14 =
    _signals_T_1 | _signals_T_3 | _signals_T_144_isJal | _signals_T_143_asel | _GEN_10;	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:117:19, :118:19, :120:19, :123:19
  wire [7:0][63:0] _GEN_15 =
    {{64'h0},
     {64'h0},
     {{{44{io_inst[31]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}},
     {{{32{io_inst[31]}}, io_inst[31:12], 12'h0}},
     {{{52{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}},
     {{{52{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}},
     {64'h0},
     {{{52{io_inst[31]}}, io_inst[31:20]}}};	// src/main/scala/decode.scala:40:28, :206:12, :210:34, :211:{30,36,41,50,61}, :212:{30,36,41,50,61,75}, :213:{30,36,41,50,61,70,84}, :214:{30,36,41,50,61}, :215:{30,36,41,50,61,75,85}
  assign io_imm =
    _GEN_15[_GEN_12
              ? 3'h4
              : _signals_T_144_isJal
                  ? 3'h5
                  : _signals_T_143_asel
                      ? 3'h0
                      : _GEN_9
                          ? 3'h3
                          : _GEN_7
                              ? 3'h0
                              : _signals_T_126_memWe
                                  ? 3'h2
                                  : _GEN_4
                                      ? 3'h0
                                      : _GEN_3
                                          ? 3'h1
                                          : _signals_T_81 | _signals_T_83 | _signals_T_85
                                            | _signals_T_103_bsel
                                              ? 3'h0
                                              : {2'h0,
                                                 _signals_T_89 | _signals_T_91
                                                   | _signals_T_93 | _signals_T_95
                                                   | _signals_T_98_cut32}];	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:18:20, :40:28, :120:19, :123:19, :151:19, :174:19, :177:19, :180:19, :183:19, :187:19, :190:19, :193:19, :196:19, :199:19, :206:12, :210:34, :211:30, :212:30, :213:30, :214:30, :215:30
  assign io_sig_asel =
    ~_signals_T_1 & (_signals_T_3 | _signals_T_144_isJal | _signals_T_143_asel);	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:117:19, :118:19, :120:19, :123:19
  assign io_sig_bsel =
    _GEN_13 | ~_GEN_10
    & (_signals_T_29 | ~_signals_T_31
       & (_signals_T_33 | ~_GEN_6
          & (_signals_T_126_memWe | _GEN_4 | ~_GEN_3
             & (_signals_T_81 | _signals_T_83 | _signals_T_85 | _signals_T_103_bsel))));	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:142:19, :145:19, :146:19, :151:19, :174:19, :177:19, :180:19, :183:19
  assign io_sig_osel =
    _GEN_14 ? 2'h0 : _signals_T_29 ? 2'h1 : _signals_T_31 ? 2'h0 : {1'h0, _signals_T_33};	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:40:28, :69:16, :142:19, :145:19, :146:19
  assign io_sig_memEn =
    ~_GEN_14
    & (_signals_T_29 | ~_signals_T_31 & (_signals_T_33 | ~_GEN_6 & _signals_T_126_memWe));	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:142:19, :145:19, :146:19, :151:19
  assign io_sig_memWe =
    ~(_signals_T_1 | _signals_T_3 | _signals_T_144_isJal | _signals_T_143_asel
      | _signals_T_9 | _signals_T_11 | _signals_T_13 | _signals_T_15 | _signals_T_17
      | _signals_T_19 | _GEN_7) & _signals_T_126_memWe;	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:117:19, :118:19, :120:19, :123:19, :127:19, :128:19, :129:19, :130:19, :131:19, :134:19, :151:19
  assign io_sig_rdWe =
    _GEN_13 | ~_GEN_10
    & (_signals_T_29 | ~_signals_T_31
       & (_signals_T_33
          | ~(_signals_T_35 | _signals_T_37 | _signals_T_39 | _signals_T_126_memWe)
          & (_GEN_5 | _signals_T_98_cut32)));	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:142:19, :145:19, :146:19, :148:19, :149:19, :150:19, :151:19, :199:19
  assign io_sig_brCond =
    _GEN_12
      ? 5'h0
      : _GEN_11
          ? 5'h1F
          : _signals_T_9
              ? 5'h4
              : _signals_T_11
                  ? 5'h1B
                  : _signals_T_13
                      ? 5'h10
                      : _signals_T_15
                          ? 5'h6
                          : _signals_T_17 ? 5'h8 : _signals_T_19 ? 5'h5 : 5'h0;	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:40:28, :82:17, :85:18, :127:19, :128:19, :129:19, :130:19, :131:19, :134:19
  assign io_sig_aluop =
    _signals_T_1
      ? 4'hE
      : _signals_T_3
          ? 4'h0
          : _GEN_11
              ? 4'hF
              : _signals_T_9 | _signals_T_11 | _signals_T_13 | _signals_T_15
                | _signals_T_17 | _signals_T_19 | _signals_T_21 | _signals_T_23
                | _signals_T_25 | _signals_T_27 | _signals_T_29 | _signals_T_31
                | _signals_T_33 | _signals_T_35 | _signals_T_37 | _signals_T_39
                | _signals_T_126_memWe | _signals_T_43
                  ? 4'h0
                  : _signals_T_45
                      ? 4'h2
                      : _signals_T_47
                          ? 4'h3
                          : _signals_T_49
                              ? 4'h4
                              : _signals_T_51
                                  ? 4'h6
                                  : _signals_T_53
                                      ? 4'h7
                                      : _signals_T_55
                                          ? 4'h1
                                          : _signals_T_57
                                              ? 4'h5
                                              : _signals_T_59
                                                  ? 4'hD
                                                  : _signals_T_61
                                                      ? 4'h0
                                                      : _signals_T_63
                                                          ? 4'h8
                                                          : _signals_T_65
                                                              ? 4'h2
                                                              : _signals_T_67
                                                                  ? 4'h3
                                                                  : _signals_T_69
                                                                      ? 4'h4
                                                                      : _signals_T_71
                                                                          ? 4'h6
                                                                          : _signals_T_73
                                                                              ? 4'h7
                                                                              : _signals_T_75
                                                                                  ? 4'h1
                                                                                  : _signals_T_77
                                                                                      ? 4'h5
                                                                                      : _signals_T_79
                                                                                          ? 4'hD
                                                                                          : _signals_T_81
                                                                                              ? 4'h0
                                                                                              : _signals_T_83
                                                                                                  ? 4'h1
                                                                                                  : _signals_T_85
                                                                                                      ? 4'h5
                                                                                                      : _signals_T_103_bsel
                                                                                                          ? 4'hD
                                                                                                          : _signals_T_89
                                                                                                              ? 4'h0
                                                                                                              : _signals_T_91
                                                                                                                  ? 4'h8
                                                                                                                  : _signals_T_93
                                                                                                                      ? 4'h1
                                                                                                                      : _signals_T_95
                                                                                                                          ? 4'h5
                                                                                                                          : _signals_T_98_cut32
                                                                                                                              ? 4'hD
                                                                                                                              : 4'h0;	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:40:28, :82:17, :85:18, :117:19, :118:19, :127:19, :128:19, :129:19, :130:19, :131:19, :134:19, :138:19, :139:19, :140:19, :141:19, :142:19, :145:19, :146:19, :148:19, :149:19, :150:19, :151:19, :153:19, :154:19, :155:19, :156:19, :157:19, :158:19, :159:19, :160:19, :161:19, :163:19, :164:19, :165:19, :166:19, :167:19, :168:19, :169:19, :170:19, :171:19, :172:19, :174:19, :177:19, :180:19, :183:19, :187:19, :190:19, :193:19, :196:19, :199:19
  assign io_sig_isJal = ~_GEN_12 & _signals_T_144_isJal;	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:120:19
  assign io_sig_cut32 =
    ~_GEN_14
    & (_signals_T_29
       | ~(_signals_T_31 | _signals_T_33 | _signals_T_35 | _signals_T_37 | _signals_T_39
           | _signals_T_126_memWe | _signals_T_43 | _signals_T_45 | _signals_T_47
           | _signals_T_49 | _signals_T_51 | _signals_T_53 | _signals_T_55 | _signals_T_57
           | _signals_T_59 | _GEN_3) & (_GEN_2 | _signals_T_98_cut32));	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:142:19, :145:19, :146:19, :148:19, :149:19, :150:19, :151:19, :153:19, :154:19, :155:19, :156:19, :157:19, :158:19, :159:19, :160:19, :161:19, :199:19
  assign io_sig_err =
    ~(_signals_T_1 | _signals_T_3 | _signals_T_144_isJal | _signals_T_143_asel | _GEN_9)
    & (_GEN_8 | ~_signals_T_29
       & (_signals_T_31 | ~_signals_T_33
          & (_GEN_6 | ~(_signals_T_126_memWe | _GEN_5) & ~_signals_T_98_cut32)));	// <stdin>:49:10, src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/decode.scala:40:28, :94:15, :117:19, :118:19, :120:19, :123:19, :142:19, :145:19, :146:19, :151:19, :199:19
endmodule

module Regfile(	// <stdin>:1273:10
  input         clock,	// <stdin>:1274:11
  input  [4:0]  io_rs1_addr,	// src/main/scala/regfile.scala:30:16
                io_rs2_addr,	// src/main/scala/regfile.scala:30:16
                io_rd_addr,	// src/main/scala/regfile.scala:30:16
  input  [63:0] io_rd_data,	// src/main/scala/regfile.scala:30:16
  input         io_rd_we,	// src/main/scala/regfile.scala:30:16
  output [63:0] io_rs1_data,	// src/main/scala/regfile.scala:30:16
                io_rs2_data,	// src/main/scala/regfile.scala:30:16
                io_gpr_0,	// src/main/scala/regfile.scala:30:16
                io_gpr_1,	// src/main/scala/regfile.scala:30:16
                io_gpr_2,	// src/main/scala/regfile.scala:30:16
                io_gpr_3,	// src/main/scala/regfile.scala:30:16
                io_gpr_4,	// src/main/scala/regfile.scala:30:16
                io_gpr_5,	// src/main/scala/regfile.scala:30:16
                io_gpr_6,	// src/main/scala/regfile.scala:30:16
                io_gpr_7,	// src/main/scala/regfile.scala:30:16
                io_gpr_8,	// src/main/scala/regfile.scala:30:16
                io_gpr_9,	// src/main/scala/regfile.scala:30:16
                io_gpr_10,	// src/main/scala/regfile.scala:30:16
                io_gpr_11,	// src/main/scala/regfile.scala:30:16
                io_gpr_12,	// src/main/scala/regfile.scala:30:16
                io_gpr_13,	// src/main/scala/regfile.scala:30:16
                io_gpr_14,	// src/main/scala/regfile.scala:30:16
                io_gpr_15,	// src/main/scala/regfile.scala:30:16
                io_gpr_16,	// src/main/scala/regfile.scala:30:16
                io_gpr_17,	// src/main/scala/regfile.scala:30:16
                io_gpr_18,	// src/main/scala/regfile.scala:30:16
                io_gpr_19,	// src/main/scala/regfile.scala:30:16
                io_gpr_20,	// src/main/scala/regfile.scala:30:16
                io_gpr_21,	// src/main/scala/regfile.scala:30:16
                io_gpr_22,	// src/main/scala/regfile.scala:30:16
                io_gpr_23,	// src/main/scala/regfile.scala:30:16
                io_gpr_24,	// src/main/scala/regfile.scala:30:16
                io_gpr_25,	// src/main/scala/regfile.scala:30:16
                io_gpr_26,	// src/main/scala/regfile.scala:30:16
                io_gpr_27,	// src/main/scala/regfile.scala:30:16
                io_gpr_28,	// src/main/scala/regfile.scala:30:16
                io_gpr_29,	// src/main/scala/regfile.scala:30:16
                io_gpr_30,	// src/main/scala/regfile.scala:30:16
                io_gpr_31	// src/main/scala/regfile.scala:30:16
);

  reg  [63:0]       regs_0;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_1;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_2;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_3;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_4;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_5;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_6;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_7;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_8;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_9;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_10;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_11;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_12;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_13;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_14;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_15;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_16;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_17;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_18;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_19;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_20;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_21;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_22;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_23;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_24;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_25;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_26;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_27;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_28;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_29;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_30;	// src/main/scala/regfile.scala:32:19
  reg  [63:0]       regs_31;	// src/main/scala/regfile.scala:32:19
  wire [31:0][63:0] _GEN =
    {{regs_31},
     {regs_30},
     {regs_29},
     {regs_28},
     {regs_27},
     {regs_26},
     {regs_25},
     {regs_24},
     {regs_23},
     {regs_22},
     {regs_21},
     {regs_20},
     {regs_19},
     {regs_18},
     {regs_17},
     {regs_16},
     {regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};	// src/main/scala/regfile.scala:32:19, :38:20
  always @(posedge clock) begin	// <stdin>:1274:11
    automatic logic _T_3 = io_rd_we & (|io_rd_addr);	// src/main/scala/regfile.scala:42:{21,36}
    if (_T_3 & io_rd_addr == 5'h0)	// src/main/scala/regfile.scala:32:19, :35:21, :42:{21,46}, :43:26
      regs_0 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_1 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h2)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_2 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h3)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_3 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h4)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_4 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h5)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_5 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h6)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_6 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h7)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_7 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h8)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_8 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h9)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_9 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hA)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_10 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hB)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_11 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hC)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_12 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hD)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_13 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hE)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_14 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'hF)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_15 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h10)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_16 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h11)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_17 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h12)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_18 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h13)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_19 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h14)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_20 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h15)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_21 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h16)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_22 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h17)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_23 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h18)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_24 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h19)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_25 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1A)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_26 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1B)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_27 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1C)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_28 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1D)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_29 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & io_rd_addr == 5'h1E)	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_30 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
    if (_T_3 & (&io_rd_addr))	// src/main/scala/regfile.scala:32:19, :42:{21,46}, :43:26
      regs_31 <= io_rd_data;	// src/main/scala/regfile.scala:32:19
  end // always @(posedge)
  `ifndef SYNTHESIS	// <stdin>:1273:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:1273:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:1273:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_0;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_1;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_2;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_3;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_4;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_5;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_6;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_7;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_8;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_9;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_10;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_11;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_12;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_13;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_14;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_15;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_16;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_17;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_18;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_19;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_20;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_21;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_22;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_23;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_24;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_25;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_26;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_27;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_28;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_29;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_30;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_31;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_32;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_33;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_34;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_35;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_36;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_37;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_38;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_39;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_40;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_41;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_42;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_43;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_44;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_45;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_46;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_47;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_48;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_49;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_50;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_51;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_52;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_53;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_54;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_55;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_56;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_57;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_58;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_59;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_60;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_61;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_62;	// <stdin>:1273:10
      automatic logic [31:0] _RANDOM_63;	// <stdin>:1273:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:1273:10
        `INIT_RANDOM_PROLOG_	// <stdin>:1273:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:1273:10
        _RANDOM_0 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_1 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_2 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_3 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_4 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_5 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_6 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_7 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_8 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_9 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_10 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_11 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_12 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_13 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_14 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_15 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_16 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_17 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_18 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_19 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_20 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_21 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_22 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_23 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_24 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_25 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_26 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_27 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_28 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_29 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_30 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_31 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_32 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_33 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_34 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_35 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_36 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_37 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_38 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_39 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_40 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_41 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_42 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_43 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_44 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_45 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_46 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_47 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_48 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_49 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_50 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_51 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_52 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_53 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_54 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_55 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_56 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_57 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_58 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_59 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_60 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_61 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_62 = `RANDOM;	// <stdin>:1273:10
        _RANDOM_63 = `RANDOM;	// <stdin>:1273:10
        regs_0 = {_RANDOM_0, _RANDOM_1};	// src/main/scala/regfile.scala:32:19
        regs_1 = {_RANDOM_2, _RANDOM_3};	// src/main/scala/regfile.scala:32:19
        regs_2 = {_RANDOM_4, _RANDOM_5};	// src/main/scala/regfile.scala:32:19
        regs_3 = {_RANDOM_6, _RANDOM_7};	// src/main/scala/regfile.scala:32:19
        regs_4 = {_RANDOM_8, _RANDOM_9};	// src/main/scala/regfile.scala:32:19
        regs_5 = {_RANDOM_10, _RANDOM_11};	// src/main/scala/regfile.scala:32:19
        regs_6 = {_RANDOM_12, _RANDOM_13};	// src/main/scala/regfile.scala:32:19
        regs_7 = {_RANDOM_14, _RANDOM_15};	// src/main/scala/regfile.scala:32:19
        regs_8 = {_RANDOM_16, _RANDOM_17};	// src/main/scala/regfile.scala:32:19
        regs_9 = {_RANDOM_18, _RANDOM_19};	// src/main/scala/regfile.scala:32:19
        regs_10 = {_RANDOM_20, _RANDOM_21};	// src/main/scala/regfile.scala:32:19
        regs_11 = {_RANDOM_22, _RANDOM_23};	// src/main/scala/regfile.scala:32:19
        regs_12 = {_RANDOM_24, _RANDOM_25};	// src/main/scala/regfile.scala:32:19
        regs_13 = {_RANDOM_26, _RANDOM_27};	// src/main/scala/regfile.scala:32:19
        regs_14 = {_RANDOM_28, _RANDOM_29};	// src/main/scala/regfile.scala:32:19
        regs_15 = {_RANDOM_30, _RANDOM_31};	// src/main/scala/regfile.scala:32:19
        regs_16 = {_RANDOM_32, _RANDOM_33};	// src/main/scala/regfile.scala:32:19
        regs_17 = {_RANDOM_34, _RANDOM_35};	// src/main/scala/regfile.scala:32:19
        regs_18 = {_RANDOM_36, _RANDOM_37};	// src/main/scala/regfile.scala:32:19
        regs_19 = {_RANDOM_38, _RANDOM_39};	// src/main/scala/regfile.scala:32:19
        regs_20 = {_RANDOM_40, _RANDOM_41};	// src/main/scala/regfile.scala:32:19
        regs_21 = {_RANDOM_42, _RANDOM_43};	// src/main/scala/regfile.scala:32:19
        regs_22 = {_RANDOM_44, _RANDOM_45};	// src/main/scala/regfile.scala:32:19
        regs_23 = {_RANDOM_46, _RANDOM_47};	// src/main/scala/regfile.scala:32:19
        regs_24 = {_RANDOM_48, _RANDOM_49};	// src/main/scala/regfile.scala:32:19
        regs_25 = {_RANDOM_50, _RANDOM_51};	// src/main/scala/regfile.scala:32:19
        regs_26 = {_RANDOM_52, _RANDOM_53};	// src/main/scala/regfile.scala:32:19
        regs_27 = {_RANDOM_54, _RANDOM_55};	// src/main/scala/regfile.scala:32:19
        regs_28 = {_RANDOM_56, _RANDOM_57};	// src/main/scala/regfile.scala:32:19
        regs_29 = {_RANDOM_58, _RANDOM_59};	// src/main/scala/regfile.scala:32:19
        regs_30 = {_RANDOM_60, _RANDOM_61};	// src/main/scala/regfile.scala:32:19
        regs_31 = {_RANDOM_62, _RANDOM_63};	// src/main/scala/regfile.scala:32:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:1273:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:1273:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_rs1_data = io_rs1_addr == 5'h0 ? 64'h0 : _GEN[io_rs1_addr];	// <stdin>:1273:10, src/main/scala/regfile.scala:35:{21,30}, :36:20, :38:20
  assign io_rs2_data = io_rs2_addr == 5'h0 ? 64'h0 : _GEN[io_rs2_addr];	// <stdin>:1273:10, src/main/scala/regfile.scala:35:{21,30}, :36:20, :38:20
  assign io_gpr_0 = regs_0;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_1 = regs_1;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_2 = regs_2;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_3 = regs_3;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_4 = regs_4;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_5 = regs_5;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_6 = regs_6;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_7 = regs_7;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_8 = regs_8;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_9 = regs_9;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_10 = regs_10;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_11 = regs_11;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_12 = regs_12;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_13 = regs_13;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_14 = regs_14;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_15 = regs_15;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_16 = regs_16;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_17 = regs_17;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_18 = regs_18;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_19 = regs_19;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_20 = regs_20;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_21 = regs_21;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_22 = regs_22;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_23 = regs_23;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_24 = regs_24;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_25 = regs_25;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_26 = regs_26;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_27 = regs_27;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_28 = regs_28;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_29 = regs_29;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_30 = regs_30;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
  assign io_gpr_31 = regs_31;	// <stdin>:1273:10, src/main/scala/regfile.scala:32:19
endmodule

module Cpu(	// <stdin>:1327:10
  input         clock,	// <stdin>:1328:11
                reset,	// <stdin>:1329:11
  input  [63:0] io_imem_rdata,	// src/main/scala/cpu.scala:29:16
                io_dmem_rdata,	// src/main/scala/cpu.scala:29:16
  output [63:0] io_pc,	// src/main/scala/cpu.scala:29:16
  output [31:0] io_inst,	// src/main/scala/cpu.scala:29:16
  output [63:0] io_imem_addr,	// src/main/scala/cpu.scala:29:16
                io_imem_wdata,	// src/main/scala/cpu.scala:29:16
  output        io_imem_en,	// src/main/scala/cpu.scala:29:16
                io_imem_we,	// src/main/scala/cpu.scala:29:16
  output [63:0] io_dmem_addr,	// src/main/scala/cpu.scala:29:16
                io_dmem_wdata,	// src/main/scala/cpu.scala:29:16
  output        io_dmem_en,	// src/main/scala/cpu.scala:29:16
                io_dmem_we,	// src/main/scala/cpu.scala:29:16
  output [63:0] io_gpr_0,	// src/main/scala/cpu.scala:29:16
                io_gpr_1,	// src/main/scala/cpu.scala:29:16
                io_gpr_2,	// src/main/scala/cpu.scala:29:16
                io_gpr_3,	// src/main/scala/cpu.scala:29:16
                io_gpr_4,	// src/main/scala/cpu.scala:29:16
                io_gpr_5,	// src/main/scala/cpu.scala:29:16
                io_gpr_6,	// src/main/scala/cpu.scala:29:16
                io_gpr_7,	// src/main/scala/cpu.scala:29:16
                io_gpr_8,	// src/main/scala/cpu.scala:29:16
                io_gpr_9,	// src/main/scala/cpu.scala:29:16
                io_gpr_10,	// src/main/scala/cpu.scala:29:16
                io_gpr_11,	// src/main/scala/cpu.scala:29:16
                io_gpr_12,	// src/main/scala/cpu.scala:29:16
                io_gpr_13,	// src/main/scala/cpu.scala:29:16
                io_gpr_14,	// src/main/scala/cpu.scala:29:16
                io_gpr_15,	// src/main/scala/cpu.scala:29:16
                io_gpr_16,	// src/main/scala/cpu.scala:29:16
                io_gpr_17,	// src/main/scala/cpu.scala:29:16
                io_gpr_18,	// src/main/scala/cpu.scala:29:16
                io_gpr_19,	// src/main/scala/cpu.scala:29:16
                io_gpr_20,	// src/main/scala/cpu.scala:29:16
                io_gpr_21,	// src/main/scala/cpu.scala:29:16
                io_gpr_22,	// src/main/scala/cpu.scala:29:16
                io_gpr_23,	// src/main/scala/cpu.scala:29:16
                io_gpr_24,	// src/main/scala/cpu.scala:29:16
                io_gpr_25,	// src/main/scala/cpu.scala:29:16
                io_gpr_26,	// src/main/scala/cpu.scala:29:16
                io_gpr_27,	// src/main/scala/cpu.scala:29:16
                io_gpr_28,	// src/main/scala/cpu.scala:29:16
                io_gpr_29,	// src/main/scala/cpu.scala:29:16
                io_gpr_30,	// src/main/scala/cpu.scala:29:16
                io_gpr_31,	// src/main/scala/cpu.scala:29:16
  output        io_err	// src/main/scala/cpu.scala:29:16
);

  wire [63:0] _regfile_io_rs1_data;	// src/main/scala/cpu.scala:37:25
  wire [63:0] _regfile_io_rs2_data;	// src/main/scala/cpu.scala:37:25
  wire [63:0] _decode_io_imm;	// src/main/scala/cpu.scala:36:25
  wire        _decode_io_sig_asel;	// src/main/scala/cpu.scala:36:25
  wire        _decode_io_sig_bsel;	// src/main/scala/cpu.scala:36:25
  wire [1:0]  _decode_io_sig_osel;	// src/main/scala/cpu.scala:36:25
  wire        _decode_io_sig_rdWe;	// src/main/scala/cpu.scala:36:25
  wire [4:0]  _decode_io_sig_brCond;	// src/main/scala/cpu.scala:36:25
  wire [3:0]  _decode_io_sig_aluop;	// src/main/scala/cpu.scala:36:25
  wire        _decode_io_sig_isJal;	// src/main/scala/cpu.scala:36:25
  wire        _decode_io_sig_cut32;	// src/main/scala/cpu.scala:36:25
  wire [63:0] _alu_io_out;	// src/main/scala/cpu.scala:35:25
  wire [4:0]  _alu_io_cmp;	// src/main/scala/cpu.scala:35:25
  reg  [63:0] pc;	// src/main/scala/cpu.scala:31:23
  reg  [63:0] ipc;	// src/main/scala/cpu.scala:32:23
  reg  [31:0] inst;	// src/main/scala/cpu.scala:33:23
  wire [63:0] res = _decode_io_sig_osel == 2'h0 ? _alu_io_out : io_dmem_rdata;	// src/main/scala/cpu.scala:35:25, :36:25, :51:{18,38}
  always @(posedge clock) begin	// <stdin>:1328:11
    if (reset) begin	// <stdin>:1328:11
      pc <= 64'h80000000;	// src/main/scala/cpu.scala:31:23
      inst <= 32'h13;	// src/main/scala/cpu.scala:33:23
    end
    else begin	// <stdin>:1328:11
      if (|(_decode_io_sig_brCond & _alu_io_cmp))	// src/main/scala/cpu.scala:35:25, :36:25, :72:{31,45}
        pc <= (_decode_io_sig_isJal ? pc : _regfile_io_rs1_data) + _decode_io_imm;	// src/main/scala/cpu.scala:31:23, :36:25, :37:25, :73:{12,59}
      else	// src/main/scala/cpu.scala:72:45
        pc <= pc + 64'h4;	// src/main/scala/cpu.scala:31:23, :74:12
      if (pc[2])	// src/main/scala/cpu.scala:31:23, :33:30
        inst <= io_imem_rdata[63:32];	// src/main/scala/cpu.scala:33:{23,48}
      else	// src/main/scala/cpu.scala:33:30
        inst <= io_imem_rdata[31:0];	// src/main/scala/cpu.scala:33:{23,71}
    end
    ipc <= pc;	// src/main/scala/cpu.scala:31:23, :32:23
  end // always @(posedge)
  `ifndef SYNTHESIS	// <stdin>:1327:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:1327:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:1327:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:1327:10
      automatic logic [31:0] _RANDOM_0;	// <stdin>:1327:10
      automatic logic [31:0] _RANDOM_1;	// <stdin>:1327:10
      automatic logic [31:0] _RANDOM_2;	// <stdin>:1327:10
      automatic logic [31:0] _RANDOM_3;	// <stdin>:1327:10
      automatic logic [31:0] _RANDOM_4;	// <stdin>:1327:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:1327:10
        `INIT_RANDOM_PROLOG_	// <stdin>:1327:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:1327:10
        _RANDOM_0 = `RANDOM;	// <stdin>:1327:10
        _RANDOM_1 = `RANDOM;	// <stdin>:1327:10
        _RANDOM_2 = `RANDOM;	// <stdin>:1327:10
        _RANDOM_3 = `RANDOM;	// <stdin>:1327:10
        _RANDOM_4 = `RANDOM;	// <stdin>:1327:10
        pc = {_RANDOM_0, _RANDOM_1};	// src/main/scala/cpu.scala:31:23
        ipc = {_RANDOM_2, _RANDOM_3};	// src/main/scala/cpu.scala:32:23
        inst = _RANDOM_4;	// src/main/scala/cpu.scala:33:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:1327:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:1327:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Alu alu (	// src/main/scala/cpu.scala:35:25
    .io_opcode (_decode_io_sig_aluop),	// src/main/scala/cpu.scala:36:25
    .io_ua     (_decode_io_sig_asel ? ipc : _regfile_io_rs1_data),	// src/main/scala/cpu.scala:32:23, :36:25, :37:25, :59:25
    .io_ub     (_decode_io_sig_bsel ? _decode_io_imm : _regfile_io_rs2_data),	// src/main/scala/cpu.scala:36:25, :37:25, :60:25
    .io_out    (_alu_io_out),
    .io_cmp    (_alu_io_cmp)
  );
  Decode decode (	// src/main/scala/cpu.scala:36:25
    .io_inst       (inst),	// src/main/scala/cpu.scala:33:23
    .io_imm        (_decode_io_imm),
    .io_sig_asel   (_decode_io_sig_asel),
    .io_sig_bsel   (_decode_io_sig_bsel),
    .io_sig_osel   (_decode_io_sig_osel),
    .io_sig_memEn  (io_dmem_en),
    .io_sig_memWe  (io_dmem_we),
    .io_sig_rdWe   (_decode_io_sig_rdWe),
    .io_sig_brCond (_decode_io_sig_brCond),
    .io_sig_aluop  (_decode_io_sig_aluop),
    .io_sig_isJal  (_decode_io_sig_isJal),
    .io_sig_cut32  (_decode_io_sig_cut32),
    .io_sig_err    (io_err)
  );
  Regfile regfile (	// src/main/scala/cpu.scala:37:25
    .clock       (clock),
    .io_rs1_addr (inst[19:15]),	// src/main/scala/cpu.scala:33:23, :53:32
    .io_rs2_addr (inst[24:20]),	// src/main/scala/cpu.scala:33:23, :54:32
    .io_rd_addr  (inst[11:7]),	// src/main/scala/cpu.scala:33:23, :55:32
    .io_rd_data  (_decode_io_sig_cut32 ? {{32{res[31]}}, res[31:0]} : res),	// src/main/scala/cpu.scala:36:25, :51:18, :56:{31,56,61,69,79}
    .io_rd_we    (_decode_io_sig_rdWe),	// src/main/scala/cpu.scala:36:25
    .io_rs1_data (_regfile_io_rs1_data),
    .io_rs2_data (_regfile_io_rs2_data),
    .io_gpr_0    (io_gpr_0),
    .io_gpr_1    (io_gpr_1),
    .io_gpr_2    (io_gpr_2),
    .io_gpr_3    (io_gpr_3),
    .io_gpr_4    (io_gpr_4),
    .io_gpr_5    (io_gpr_5),
    .io_gpr_6    (io_gpr_6),
    .io_gpr_7    (io_gpr_7),
    .io_gpr_8    (io_gpr_8),
    .io_gpr_9    (io_gpr_9),
    .io_gpr_10   (io_gpr_10),
    .io_gpr_11   (io_gpr_11),
    .io_gpr_12   (io_gpr_12),
    .io_gpr_13   (io_gpr_13),
    .io_gpr_14   (io_gpr_14),
    .io_gpr_15   (io_gpr_15),
    .io_gpr_16   (io_gpr_16),
    .io_gpr_17   (io_gpr_17),
    .io_gpr_18   (io_gpr_18),
    .io_gpr_19   (io_gpr_19),
    .io_gpr_20   (io_gpr_20),
    .io_gpr_21   (io_gpr_21),
    .io_gpr_22   (io_gpr_22),
    .io_gpr_23   (io_gpr_23),
    .io_gpr_24   (io_gpr_24),
    .io_gpr_25   (io_gpr_25),
    .io_gpr_26   (io_gpr_26),
    .io_gpr_27   (io_gpr_27),
    .io_gpr_28   (io_gpr_28),
    .io_gpr_29   (io_gpr_29),
    .io_gpr_30   (io_gpr_30),
    .io_gpr_31   (io_gpr_31)
  );
  assign io_pc = pc;	// <stdin>:1327:10, src/main/scala/cpu.scala:31:23
  assign io_inst = inst;	// <stdin>:1327:10, src/main/scala/cpu.scala:33:23
  assign io_imem_addr = pc & 64'hFFFFFFFFFFFFFFF8;	// <stdin>:1327:10, src/main/scala/cpu.scala:31:23, :43:{25,28}
  assign io_imem_wdata = 64'h0;	// <stdin>:1327:10, src/main/scala/cpu.scala:44:19
  assign io_imem_en = 1'h1;	// <stdin>:1327:10, src/main/scala/cpu.scala:45:19
  assign io_imem_we = 1'h0;	// <stdin>:1327:10, src/main/scala/cpu.scala:32:23
  assign io_dmem_addr = _alu_io_out;	// <stdin>:1327:10, src/main/scala/cpu.scala:35:25
  assign io_dmem_wdata = _regfile_io_rs2_data;	// <stdin>:1327:10, src/main/scala/cpu.scala:37:25
endmodule

